apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-inference-logger

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres.yaml
  - app.yaml
  - ingress.yaml
  - migration-job.yaml
